### ISSUE TITLE
Homeassistant function async_config_entry_first_refresh deprecation messages

### ISSUE THREAD

**Issue by vanheso159** [hasscc/catlink#36]
2 messages received in HA logs after deploying the integration:

2025-01-08 14:45:03.317 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'catlink' uses `async_config_entry_first_refresh`, which is only supported for coordinators with a config entry at custom_components/catlink/__init__.py, line 39: await coordinator.async_config_entry_first_refresh(). This will stop working in Home Assistant 2025.11, please create a bug report at https://github.com/hasscc/catlink/issues

2025-01-08 14:45:04.336 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'catlink' uses `async_config_entry_first_refresh`, which is only supported for coordinators with a config entry at custom_components/catlink/modules/scooper_device.py, line 49: await self.coordinator_logs.async_config_entry_first_refresh(). This will stop working in Home Assistant 2025.11, please create a bug report at https://github.com/hasscc/catlink/issues

HA version info:
Core 2024.12.5
Supervisor 2024.12.3
Operating System 14.1
Frontend 20241127.8

**Comment by steuerzentrale** [comment]
Hi there

I just got this error using Home Assistant OS core-2025.6.1 @milosljubenovic mind having a look into it? happy to help with testing etc.

Logger: homeassistant.config_entries
Quelle: config_entries.py:749
Erstmals aufgetreten: 15. Juni 2025 um 14:23:50 (2 Vorkommnisse)
Zuletzt protokolliert: 10:50:03

Error setting up entry CatLink for catlink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/catlink/__init__.py", line 87, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by steuerzentrale** [comment]
any news on this one? still happy to test, help, however I dont have knowledge with coding :(
